# -- HTTP proxy information for knative
http_proxy: ""
# -- HTTPS proxy information for knative
https_proxy: ""
# -- No proxy information for knative
no_proxy: "localhost,127.0.0.1,10.0.0.0/8,.svc,.cluster.local"

# -- Replicas for knative components
replicas: 1

defaults:
  # -- default timeout for knative functions in seconds
  timeout_seconds: "900"
  # -- maximum timeout for knative functions in seconds
  max_timeout_seconds: "7200"

autoscaler:
  grace_period: "120s"
  retention_period: "120s"
  max_scale: "5"

deployment:
  skip_tag: "kind.local,ko.local,dev.local,localhost:5000,localhost:31212"
