# -- HTTP proxy information for knative
http_proxy: ""
# -- HTTPS proxy information for knative
https_proxy: ""
# -- No proxy information for knative
no_proxy: "localhost,127.0.0.1,10.0.0.0/8,.svc,.cluster.local"

# -- Replicas for knative components
replicas: 1

defaults:
  # -- default timeout for knative functions in seconds
  timeout_seconds: "900"
  # -- maximum timeout for knative functions in seconds
  max_timeout_seconds: "7200"
  # -- cpu requests for direktiv sidecar
  revision_cpu_request: "50m"

autoscaler:
  grace_period: "120s"
  retention_period: "120s"
  max_scale: "5"
  initial_scale: "0"
  allow_zero_initial_scale: "true"

deployment:
  skip_tag: "kind.local,ko.local,dev.local,localhost:5000,localhost:31212"

controller:
  # -- CA certifcate for self-signed certificate registries
  ca: none

envoy:
  containers:
    shutdownmanager:
      resources:
        requests:
          cpu: "40m"
          memory: "40Mi"
        limits:
          cpu: "400m"
          memory: "400Mi"
    envoy:
      resources:
        requests:
          cpu: "200m"
          memory: "200Mi"
        limits:
          cpu: "500m"
          memory: "500Mi"
netcontourcontroller:
  containers:
    controller:
      resources:
        requests:
          cpu: "40m"
          memory: "400Mi"
        limits:
          cpu: "400m"
          memory: "400Mi"
activator:
  containers:
    activator:
      resources:
        requests:
          cpu: "300m"
          memory: "60Mi"
        limits:
          cpu: "1"
          memory: "600Mi"
    autoscaler:
      resources:
        requests:
          cpu: "100m"
          memory: "100Mi"
        limits:
          cpu: "1"
          memory: "1000Mi"
    controller:
      resources:
        requests:
          cpu: "100m"
          memory: "100Mi"
        limits:
          cpu: "1"
          memory: "1000Mi"
    domainmapping:
      resources:
        requests:
          cpu: "30m"
          memory: "40Mi"
        limits:
          cpu: "300m"
          memory: "400Mi"
    domainmappingwebhook:
      resources:
        requests:
          cpu: "100m"
          memory: "100Mi"
        limits:
          cpu: "500m"
          memory: "500Mi"
    webhook:
      resources:
        requests:
          cpu: "100m"
          memory: "100Mi"
        limits:
          cpu: "500m"
          memory: "500Mi"