apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "direktiv.fullname" . }}-config-frontend
  labels:
    {{- include "direktiv.labels" . | nindent 4 }}
data:
  default.conf: |
      lua_shared_dict discovery 1m;
      lua_shared_dict jwks 1m;

      server {
        listen 2304;
        
        resolver {{ .Values.frontend.nginx.resolver }}

        lua_ssl_trusted_certificate /etc/ssl/certs/ca-certificates.crt;
        lua_ssl_verify_depth 5;

        root /usr/share/nginx/html;

        location / {
          try_files $uri /index.html;  
          {{ .Values.frontend.nginx.config | nindent 10 }}
        }
      }


  direktiv.yaml: |
    log:
      json: {{ .Values.frontend.logging.json }}
      api: {{ if eq .Values.frontend.logging.debug true }}debug{{- else }}info{{ end }}
    server:
      assets: /html
      {{- if ne .Values.apikey "none" }}
      apikey: {{ .Values.apikey }}
      {{- end }}
      {{- if .Values.frontend.certificate }}
      tlscert: /etc/certs/tls.crt
      tlskey: /etc/certs/tls.key
      {{- end }}
      {{- if .Values.frontend.backend.url }}
      backend: {{ .Values.frontend.backend.url }}
      {{- else }}
      backend: http://{{ include "direktiv.fullname" . }}-flow.{{ .Release.Namespace }}:6665
      {{- end }}
      skipverify: {{ index .Values.frontend.backend "skip-verify" }}
    {{ .Values.frontend.extraConfig }}