apiVersion: v1
kind: Service
metadata:
  name: {{ include "direktiv.fullname" . }}-bus
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
  labels:
    {{- include "direktiv.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: 4222
      name: bus
      protocol: TCP
    - port: 6222
      name: cluster
      protocol: TCP
  selector:
    {{- include "direktiv.selectorLabels" . | nindent 4 }}
