apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "direktiv.fullname" . }}-config-flow
  labels:
    {{- include "direktiv.labels" . | nindent 4 }}

data:
  flow-config.yaml: |
      functions-service: {{ include "direktiv.fullname" . }}-functions.{{ .Release.Namespace }}
      functions-timeout: {{ .Values.functions.timeout }}
      flow-service: {{ include "direktiv.fullname" . }}-flow.{{ .Release.Namespace }}
      prometheus-backend: {{ include "direktiv.fullname" . }}-prometheus-server
      {{- if .Values.opentelemetry.address }}
      {{- if .Values.opentelemetry.enabled }}
      opentelemetry-backend: {{ .Values.opentelemetry.address }}
      {{- else }}
      opentelemetry-backend: ""
      {{- end }}
      {{- else if .Values.opentelemetry.enabled }}
      opentelemetry-backend: "localhost:4317"
      {{- else }}
      opentelemetry-backend: ""
      {{- end }}
      eventing: {{ .Values.eventing.enabled }}
