apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "direktiv.fullname" . }}-config-flow
  labels:
    {{- include "direktiv.labels" . | nindent 4 }}

data:
  flow-config.yaml: |
      functions-service: {{ include "direktiv.fullname" . }}-functions.{{ .Release.Namespace }}
      functions-timeout: {{ .Values.timeout }}
      flow-service: {{ include "direktiv.fullname" . }}-flow.{{ .Release.Namespace }}
      {{- if .Values.prometheus.install }}
      prometheus-backend: {{ include "direktiv.fullname" . }}-prometheus-server.{{ .Release.Namespace }}
      {{- else }}
      prometheus-backend: {{ .Values.prometheus.backendName }}
      {{- end }}
      {{- if .Values.opentelemetry.address }}
      {{- if .Values.opentelemetry.enabled }}
      opentelemetry-backend: {{ .Values.opentelemetry.address }}
      {{- else }}
      opentelemetry-backend: ""
      {{- end }}
      {{- else if .Values.opentelemetry.enabled }}
      opentelemetry-backend: "localhost:4317"
      {{- else }}
      opentelemetry-backend: ""
      {{- end }}
      eventing: {{ .Values.eventing.enabled }}
