kind: KongIngress
apiVersion: configuration.konghq.com/v1
metadata:
  namespace: {{ .Values.functions.namespace }}
  labels:
    {{- include "direktiv.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.functions.ingressClass }}
  name: {{ include "direktiv.fullname" . }}-functions-timeout
proxy:
  protocol: http
  read_timeout: {{ .Values.functions.timeout }}
  connect_timeout: {{ .Values.functions.timeout }}
  write_timeout: {{ .Values.functions.timeout }}
  retries: 0
