{{- if .Values.ui.install }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "direktiv.fullname" . }}-ui
  labels:
    {{- include "direktiv.labelsUI" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
spec:
  ports:
    - port: 1644
      targetPort: 1644
      protocol: TCP
      name: ui
  selector:
    {{- include "direktiv.selectorLabelsUI" . | nindent 4 }}
{{- end }}